### ISSUE TITLE
Libretro port

### ISSUE THREAD

**Issue by Wintermute0110** [nxengine/nxengine-evo#120]
Can you please make a libretro port?

**Comment by isage** [comment]
No. At least not now.
But i am willing to make libretro devs life easier, refactoring cases are all about that.

**Comment by Wintermute0110** [comment]
Fair enough. Thanks a lot for your work on this fantastic port and I hope I will be able to enjoy one day on a big screen with  proper wide resolution.

**Comment by Awesomegamer6566** [comment]
I really hope for a liberto port for RetroPie

**Comment by Awesomegamer6566** [comment]
I just had an idea. What if you use the current Cave Story Liberto package and make it into NX-evo.

**Comment by isage** [comment]
Oh, silly me, how didn't i think about spending months redoing things once
again instead of fixing bugs.
You must be joking, right?

**Comment by Awesomegamer6566** [comment]
The idea is kinda stupid, but im 100% not joking

**Comment by Awesomegamer6566** [comment]
sorry.

**Comment by xordspar0** [comment]
Personally I think the libretro community should take this on. There is some talk over at libretro-nxengine of rebasing the current nxengine core on nxengine-evo instead of a fork of the original nxengine.

Since there's already some interest over in https://github.com/libretro/nxengine-libretro/issues/43, maybe this issue can be closed?

**Comment by crocket** [comment]
After talking with twinaphex, I noticed a few things.

He wants a libretro core to be a tight fit for libretro and retroarch. That's why libretro developers often create hard forks.

* He wants file I/O abstracted so that small files can be cached in RAM and do not become bottlenecks during runtime.
* He wants to eliminate as much of SDL stuff as possible for a libretro core. This means abstracting out graphics driver.
* Since libretro takes care of cross-platform portability, upstream projects' own attempts at cross-platform portability can conflict with retroarch.
* He wants stuff not related to libretro to be segregated.

If an upstream wants to support libretro, there needs to be a lot of abstractions of subsystems and delegations of things like portability.

**Comment by isage** [comment]
Whatever twinapex wants - he can do. It's opensource.
But it's up to him and libretro devs.
We don't support libretro, don't want to support libretro and won't support libretro.
Please don't bump closed issues.
