### ISSUE TITLE
Mod support - I don't get it.

### ISSUE THREAD

**Issue by Al-AmeenAdewunmi** [nxengine/nxengine-evo#156]
So it says "initial mod support". But I don't understand. How do I add mods? Do I make a folder? Do I drag and drop separate mods folders into the data folder? I don't get it.

**Comment by isage** [comment]
That's why it's "initial". There are no mods currently. It's not compatible with mods for freeware version.
Basically, you need to create `mods` folder in the data folder. Create directory for your mod inside.
Inside that mod folder, create file `mod.json` with the following format:
```
{
 "name":"Boss Rush",
 "skip-intro": true
}
```

everything else inside this mod folder should follow structure of the data folder.
