### ISSUE TITLE
license of data assets

### ISSUE THREAD

**Issue by namtsui** [nxengine/nxengine-evo#169]
What license is the assets in data/ released under (e.g., sprites.sif, Face.pbm, bkHellish.pbm, fonts)? cavestory freeware or GPLv3?

**Comment by isage** [comment]
GPLv3

**Comment by bentley** [comment]
There is no way that files like Face.pbm and the endpics, which were ripped from Cave Story, can be under GPLv3.

**Comment by isage** [comment]
The were not "ripped from", they are derivative works.

**Comment by bentley** [comment]
Derivative works of freeware can’t be GPLv3 either.

**Comment by isage** [comment]
Says who? Please, show me, where in original license (which doesn't exist)
it's prohibited to license *my* work under gpl.

GPLv3 covers only modified assets, as they include my work. Original assets
are still freeware, feel free to use them.

By your logic, assets of cs+ should be freeware too, as they are indeed a
derivative works if original freeware assets.

**Comment by bentley** [comment]
Hostility is not necessary. I like this project and want to help.

Cave Story+ has the right to redistribute and sell those assets, because Pixel explicitly granted them that right. He has not given any such rights to the general public.

**Comment by isage** [comment]
That still doesn't mean they should be freeware. If anything, it makes
them, as well as all mods illegal

**Comment by bentley** [comment]
Basically, yes. Modification is a right exclusive to the copyright holder unless granted otherwise, and Pixel has only granted that permission on a case‐by‐case basis.

Mods exist, but without a license grant, they are flying under the radar. Legally speaking, Pixel (or perhaps Nicalis) could go after them at any time. Most people are willing to live with that risk, but by policy, Debian and OpenBSD (and others like Ubuntu, Fedora, SUSE…) can’t package software with unlicensed assets.

My desire is to package nxengine-evo for OpenBSD. That could still be done, if the modified data files were not needed at runtime. That would require some work in the code, though.

**Comment by isage** [comment]
>if the modified data files were not needed at runtime

that would defeat whole purpose of nxevo. as i said in https://github.com/nxengine/nxengine-evo/issues/170 you can provide a wrapper script that grabs modified assets from github.
