### ISSUE TITLE
appimage/flatpak build scripts shouldn't call cmake build

### ISSUE THREAD

**Issue by isage** [nxengine/nxengine-evo#187]
Proper way would be for this scripts to just package contents.
That way we can safely call them from CI (right now, builds are done twice, one by CI, one by script)

**Comment by isage** [comment]
Also, @ntninja have you tested AppImage after your modifications? AFAIR libborbus is a weak dependency of SDL, so it won't be included by default in AppImage

**Comment by ntninja** [comment]
I see, what a sneeky plan to add me to the org so that you can assign me tasks… :eyes: 

Anyhow, I can tell you right off the bat that this won't be happening with Flatpak as the `flatpak-builder` is specifically designed to build everything from source in a reproducible manner. I'll check it out for AppImage however, it should be pretty simple for that one.

**Comment by ntninja** [comment]
Regarding the AppImage: Yes, I have tested it and yes `libvorbis{,file}.so` is included in the image. I had specifically checked for that after removing that hack (that I couldn't get to work on Debian anyways).

**Comment by isage** [comment]
> I see, what a sneeky plan to add me to the org so that you can assign me tasks… 
> 
> Anyhow, I can tell you right off the bat that this won't be happening with Flatpak as the `flatpak-builder` is specifically designed to build everything from source in a reproducible manner. I'll check it out for AppImage however, it should be pretty simple for that one.

Hmmm. Well, there's 'simple' buildsystem, but, as far as i understand, we don't even need to build flatpak on ci (same as with snap), am i right?

**Comment by ntninja** [comment]
> Well, there's 'simple' buildsystem, but, as far as i understand, we don't even need to build flatpak on ci (same as with snap), am i right?

I was planning on putting them here, but they can also be built and published by Flat*hub*. Albeit I'm not sure what their stance on the non-free assets is since, based on my current understanding, we don't really have any expressive licence statement on them that permits their redistribution. It's more lack of action (and encouraging words) by the original author. RedHat is quite strict about these things and Flathub is a service provided by them.

> We should, probably, organize scripts, though.

Absolutely! I think I'll change everything to use that scheme then, except that I would put the stuff you proposed for `build-scripts/platforms` directly into `build-scripts` for easier discoverability.
