### ISSUE TITLE
Achievement support.

### ISSUE THREAD

**Issue by isage** [nxengine/nxengine-evo#20]
CS+ adds new tsc command: <ACHxxxx, thus making scripts from CS+ incompatible with nxengine.
Is it worth it to properly implement achievements, or just add a no-op support for <ACH?

**Comment by Darknior** [comment]
If i understand fine, this option is important for the FRENCH translation of this game.
I prefer read french than Achievement first.
Your project is really fantastic, why don't you add your work to RETROARCH ? now it works on any support, it's really cool :) I' m on PI3 now.

**Comment by isage** [comment]
It's not really. http://www.cavestory.org/downloads/cave_story_fr_1_11.zip this one doesn't contain <ACH
Moreover, i'm currently working on a completely different format for translations (proper unicode support + gettext).

Porting this to retroarch would require ton of work, and i'm really not interested in that at this point.

**Comment by Darknior** [comment]
Thanks, yes i know this version, but it crash and don't work on RETROARCH :(
Do you know your version with all your new feature can compile on PI ?

**Comment by isage** [comment]
Yep, last time i've checked it worked fine on Pi1

**Comment by isage** [comment]
Btw, i've tested it in RPi. It should work in X, but won't in console/framebuffer, because latest SDL2 in raspbian built without RPi framebuffer support (they broke SDL2 buildsystem autodetection of RPi).

**Comment by Yukitty** [comment]
I would no-op `<ACH`, but I don't understand what you mean by "properly implementing" them otherwise? NXEngine can't exactly award Steam achivements.

Would it just pop up a unique little "got achievement" notification with no use or purpose? Would it track them on the main menu or use Game Jolt or similar? Mmmm...

I don't think CS+'s achievements are particularly "good" in terms of design, and none of the game was really built to support them. It's just another dumb thing Nicalis tacked on to try to peddle the already-finished game they bought, nothing Nicalis added actually jives well with the actual game, save for _maybe_ the second attempt at upgrading the music.
