### ISSUE TITLE
Communication channel

### ISSUE THREAD

**Issue by isage** [nxengine/nxengine-evo#215]
I understand that discord is a no-go for some people. And that's fine.
Sadly, anything beyond telegram/discord/IRC is too much for me.

IRC has gates to Matrix and Discord (well, the other way around, but anyway), and probably TG too.

Question: if we use IRC - where? I have my own semi-private server, or we can use any available irc network
Problem 1: there's no adequate mobile client for IRC
Solution: use gates from other software to irc
That raises problem 2: would it be ethical to use irc<->discord gate for example to those, who against using discord directly?

Thoughts?

**Comment by ntninja** [comment]
Since you didn't directly say it, I'm writing the below on the assumption that this will be a public room/channel. Please correct me if you had something else in mind.

> Question: if we use IRC - where? I have my own semi-private server, or we can use any available irc network

I have absolutely no preference whatsoever on this, given that the channel is public. Somebody actually using IRC should comment on whether using “unusual” IRC servers is somehow bothersome as compared to well-established ones.

> That raises problem 2: would it be ethical to use irc<->discord gate for example to those, who against using discord directly?

Again assuming public chat, I see no immediate problem with it being bridged to Discord. Not having presence on Discord would be nice of course, but I mean, we're developing a *game* here, gotta be realistic too. :wink:
(TL;DR: I'll abstain on this one, do whatever you feel is the best.)

> IRC has gates to Matrix and Discord (well, the other way around, but anyway), and probably TG too.

As for gates I'd suggest putting Matrix in the center as it has OK to great bridges to just about everything (provided that you have permissions on the channel/room in the target network) and preserves rich content (formatting, images, that kind of stuff).

Summary: Really, this is mostly about not personally joining Discord for me. If my (public) messages end up there, that is slightly unfortunate, but no big drama.

**Comment by isage** [comment]
Yeah, channel would of course be public. As for discord bridge, that's
implemented through bot, so that could allow for anonymity if required.

**Comment by ntninja** [comment]
Well, tell me the IRC channel and I'll join in over the Matrix bridge.

**Comment by isage** [comment]
Well then, #nxevo at irc.aumi.ru
6697 - ssl port, 6667 - non-secure
(if that auto-joins you to #anime-umi just part. It shouldn't, but maybe i messed up something in config)

**Comment by ntninja** [comment]
Matrix channel is at [#nxengine-evo:ninetailed.ninja](https://matrix.to/#/#nxengine-evo:ninetailed.ninja), if you make me admin in the IRC room I can also publish this in the Matrix room directory (bridge won't make admin without that on Matrix only [probably b/c nobody bothered implementing it] and working around that is something I'd prefer not doing).
