### ISSUE TITLE
Inconsistencies

### ISSUE THREAD

**Issue by isage** [nxengine/nxengine-evo#26]
I'm pretty sure there's ton of inconsistencies between nxengine and original.
Enemy behaviour, damage, physics, etc.
It would be nice if someone took upon a task of comparing original freeware version and nxengine.
Pull requests are welcome too, but with detailed description of inconsistency.

**Comment by nlburgin** [comment]
I've been playing it a while (currently at Last Cave) and for the most part it *feels* solidly identical.

However it's been a while since I last played the original, so that makes the comparison a bit harder.

One thing I've noticed is that the lvl3 sword (King's ghost attack) seems more effective against bosses than I remember. Although that could *very* easily just be my imagination.

An interesting way to non-subjectively test for identicality, though, might be to take an old TAS of the original, and somehow convert the Hourglass input movie into a format that could be played back on Nxengine.

It certainly wouldn't be the easiest way to test it, but it *would* be a very robust test because it takes the human element out of play and provides a way to compare how the two versions respond to the *exact* same inputs on the exact *same* frames. Every time it desyncs, you've uncovered a new bug!

Easier said than done, of course, so it would be quite understandable if you didn't want to do it, bit it's just a thought I had.

**Comment by isage** [comment]
Yeah, i was thinking about something like that. Hourglass format seems easy enough, guess i'll slap together some player for it.

**Comment by isage** [comment]
Ugh. It seems like i'll need to build the player into engine, because SDL uses raw evdev input and completely ignores Xorg events.

**Comment by isage** [comment]
Oh. okay. i've kinda implemented separate player for hourglass records.
And found first inconsistency right on atart: speeding up dialogs by mashing Z X doesn't work as in original.
Also, i've only found one movie: speedrun by nitsuja. Are there any others?

**Comment by nlburgin** [comment]
>SDL uses raw evdev

At the risk of introducing a new dependency, I know evdev is [scriptable through python](https://github.com/gvalkov/python-evdev); it's possible that could simplify matters as long as it's not too slow to keep up with the game.

>i've only found one movie: speedrun by nitsuja. Are there any others? 

I've found it surprisingly difficult to find any. 

I found some things for Cave Story+, and some things for Jenka's Nightmare (an old mod that won't readily run in Nxengine due to how heavily altered it is), but I doubt either of those would help.

What few other TASes I've found for the original cave story were just simple tests, and I can't seem to find the original hourglass file for any of them.

I have an old Windows XP setup in Virtualbox that I could theoretically use to record some new ones, if you want.

**Comment by isage** [comment]
> At the risk of introducing a new dependency, I know evdev is scriptable through python; 

Nah, i've already solved this with "player", that creates a virtual keyboard device through uevent and sends keys from hourglass movie. And a hook library to sync with frames.

> I've found it surprisingly difficult to find any.

Oh well. I do have an old notebook with windows, so i can probably record some replays myself.

> Does Nx currently go out of the way to use the same RNG as the original?

Original nxengine uses self-implemented RNG (i guess the same as in original game), nxengine-evo, however uses system RNG. I guess i can revert this, and monkey-patch to use seed from replay.

**Comment by nlburgin** [comment]
> Original nxengine uses self-implemented RNG (i guess the same as in original game), nxengine-evo, however uses system RNG. I guess i can revert this, and monkey-patch to use seed from replay.

I have a mild suspicion that the original cave story probably used the system RNG from windows, though this may not be compatible with Linux, OSX, or even more recent Windows. Hourglass, for its part, I think is pretty much exclusive to WinXP, since its hacky methods for encapsulating and manipulating game processes is non-portable even amongst different versions of Windows.

Although, Pixel being Pixel, I wouldn't put it past him to have written his own RNG instead.

Either way, if the original NxEngine had its own RNG instead of using the standard library, I'm guessing it was *probably* meant as a compatibility thing, though I can't vouch for how well it actually succeeded at being compatible.

I do know that PySolFC, a solitaire suite, successfully implemented a clone of old Windows default RNG, which it only uses for relatively low seed values, solely for the purpose of replicating the shuffle&deal results of MS Freecell.

**Comment by isage** [comment]
Original engine just uses windows system srand/rand. NXEngine implemented it, but it looks like slightly incorrectly. I'll revert my changes and fix rand to be the same as on windows.

**Comment by isage** [comment]
Ugh. nitsuja's replay seems impossible. Engine needs to be frame-perfect for this and right now it gets 5-10 frames faster to the point, where you can actually control Quote. Either stage transitions are faster or fadeins/fadeouts. Or both.
And i'm not sure i really want it to be frame-perfect.
However, i guess i can still test using hourglass and playing slowly.
Also, nitsuja's comments for replay are pointing out some mechanics i wasn't aware of (like that max walking speed actually oscillates)

**Comment by nlburgin** [comment]
> Also, nitsuja's comments for replay are pointing out some mechanics i wasn't aware of (like that max walking speed actually oscillates)

Interesting. It could be that you might more easily get consistency fixes from reading the commentary, than from actually trying to play back the TAS.

>And i'm not sure i really want it to be frame-perfect.
>However, i guess i can still test using hourglass and playing slowly.

Hmm... I guess there's no harm in *not* replicating some of the more obscure and unexpected behaviors of the original engine, especially if it's some crazy corner case that Pixel likely never intended.

On that note, an Hourglass recording of someone playing like a normal person might indeed be more helpful than an actual super-optimized TAS.

**Comment by nlburgin** [comment]
I just found a couple inconsistencies through manual testing. 

I loaded my save I'd been using on Nx in the original, which is currently at the Balcony.

In Nx, you can stand on the Igor's (larger rabid mimiga's) head as well as the smaller one. 

In the original, contact with the top of the Igor does damage, while the smaller one can still be stood on.

Also in Nx, the limit on how much damage Misery can take before she turns invincible and teleports seems to be *much* laxer. In Nx, I can wipe her out instantly with rapid-fire super missiles at the start of the fight. In the original, I can't do that. Also, the amount of damage I can do with the Snake before she disappears is much higher.

**Comment by nlburgin** [comment]
Okay, I think the reason it was so noticeable with Misery, was there were two issues happening at once.

One issue is, Misery doesn't turn invincible and teleport early after taking a certain amount of damage the way she's supposed to. I don't think any other bosses have this issue.

The other issue is, the Super Missile Launcher is just doing *way* too much damage. I think this is the actual reason why I thought some of the other bosses might have had a lesser version of Misery's issue.

I was playing around with the rabid mimigas on the Balcony, and in the original, the max amount of damage I could do with a single firing of the Lvl3 SML, with all 3 missiles hitting cleanly, was 38. In Nx, I could do up to *66*.

**Comment by isage** [comment]
Hm, Misery *should* teleport out when being hit for >=80hp.
But supermissile damage is indeed seems off.

**Comment by isage** [comment]
The problem with missiles (and supermissiles) is that they deal splash damage: they spawn blasts and each blast deals some damage. However, arms table in original only sets damage for blasts (and damage for missiles is set to 0). And all guides on the internet only list cumulative damage, ugh.
Back to the disasm for me, i guess.

**Comment by isage** [comment]
Hm, yep. Although Misery *should* teleport out when receiving 80 damage, i can deal 132 with machingun until she do. This is strange.

**Comment by isage** [comment]
Oh, i found (and fixed) stupid bug in Misery AI. Now she indeed teleports when receiving 84dmg from machingun.

**Comment by isage** [comment]
I've created separate issues for Missile Launcher and For Igor

**Comment by nlburgin** [comment]
Just built from git master (was previously using source release 2.6.2), and I can confirm that Misery now no longer just sits there and lets you obliterate her.

**Comment by Clownacy** [comment]
So, do you still need a hitbox drawer?

**Comment by isage** [comment]
Nah, i've already implemented it.
Sorry for bothering.
(also, i can send a PR, but my method currently conflicts with widescreen mod. and i'm not sure if someone besides me even needs it)

**Comment by isage** [comment]
So, found two more bugs, while testing missile damage:
1) Second form of Monster X doesn't show floating damage numbers (fixed)
2) Floating damage sometimes shows more damage, that actual NPC hp: lv3 rocketlauncher vs gaudis shows 16 dmg, while gaudi hp is 15. However, that might be only for gaudis, because their hp in npc.tbl is actually 1000 (?!). Need to test some more. I probably won't fix that, as it's purely cosmetical.

I'm still not sure what to do about missiles. For now i've re-implemented original buggy way of handling bullets (not committed yet, need to test some more). However, i'm not really liking that solution.

**Comment by Clownacy** [comment]
I've heard the 1000HP thing is a trick in the original engine. There's no way to change an enemy's death behaviour, so instead the game basically cheats, and gives the enemy a ludicrously high amount of health. Then the enemy itself checks if its health is below 980HP or so, and then it kills itself with a custom death sequence.

**Comment by isage** [comment]
Eh, okay. Latest (rather large) commit should fix missile damage/behaviour/hitboxes/etc.. And even almost correctly displays damage that's more than npc hp.
I really hope i haven't broken anything else

**Comment by isage** [comment]
I've put (back) in correct implementation of windows RNG.

**Comment by nlburgin** [comment]
It's less inaccurate than before, but I can still sometimes do up to 40 dmg with a single super missile firing, so it's not perfect.

[simplescreenrecorder-2018-03-09_11.23.05.mkv.zip](https://github.com/nxengine/nxengine-evo/files/1797550/simplescreenrecorder-2018-03-09_11.23.05.mkv.zip)

**Comment by isage** [comment]
That's actually right damage. Lv3 super missile launcher deals 36-40 dmg depending on when first and second/third missile hit target (and you can actually do 42 by manipulating bullet queue with another weapon and some luck). But, there may be something off with missiles pattern/acceleration, so they hit with another order/timings that original.

**Comment by Yukitty** [comment]
I'm not sure, since this is one of those RNG-based things, but it seems to me like Jenka (NPC in Sand Zone) seems to be shaking her head a LOT more often than I'm used to, sometimes it looks like she's spasming uncomfortably.

**Comment by Yukitty** [comment]
I am noticing the Missile Launcher seems to get reordered to the end of the weapon whenever you pick up Max Missiles upgrades. That's not normal, is it?

**Comment by Yukitty** [comment]
Monster X makes no pain noises.

**Comment by Yukitty** [comment]
The dummy player object (which is used for things like teleporting) does not change for Mimiga Mask.

**Comment by Yukitty** [comment]
The Whimsical Star continues to fly around and damage things during cutscenes. Including tinking against the jail cell bars and damaging freshly spawned bosses while they're still talking to you. For example, when the formless Doctor takes over the Core, Sue and Misery?

Even if ending the cutscene and actually starting the fight for some reason resets their HP, it's still pretty bad looking to have them shaking around making damage numbers while they're supposed to be standing still.

**Comment by Yukitty** [comment]
If you beat the game with the Little Man in your inventory, he's supposed to pop up before the credits(?) with a line of dialogue, saying "Hey, are you forgetting something?". but he doesn't. Where is the TSC script for that again...

**Comment by isage** [comment]
> The "shutters" and "lift" (but not the primary blast door) in the map Core are completely silent.
> If I recall, the Sun Stones in Sand Zone were also silent.
> And shouldn't be.

Hm. I've checked, and in original game shutters and lift are also silent. Sun blocks should make noise.

**Comment by isage** [comment]
Checked sunstones, and they do make sound.

**Comment by isage** [comment]
And Sue's fixed now.
I'll separate what's left into different issues.

**Comment by isage** [comment]
Hm, comment about Mr. Little is somehow gone. Is that a valid bug?
He should pop up, yes, if you beat the game with best ending and him still in the inventory

**Comment by Yukitty** [comment]
No, sorry, Mr. Little works as intended, I was just getting the wrong ending for him to care. ¯\_(ツ)_/¯ I've been getting that problem a lot, reading Sue's letter and wondering why the Jail escape block doesn't open, when you actually have to talk to Mahin again, etc.

**Comment by isage** [comment]
Yeah, you need to copy over new sprites.sif.

**Comment by Yukitty** [comment]
Oh, dur. Silly me. That's also why Chaco changed into Mahin. @_@;

sprites.sif is such a drag.

**Comment by Yukitty** [comment]
Things that don't feel right to me, but I still need to research more thuroughly:
* The level 3 sword seems like it has a bias where it attacks either in front of or behind where ghost king actually lands, rather than centered around him...
* The camera seems to be a little lower than intended, and gets even lower if the aspect ratio becomes tall, not centering the screen at all.
* Jenka's head doesn't shake as often now, but it still shakes "fast" on the occasions when it does. (I should try to get frame counts and work out if there's actually a difference there.)
* Sometimes it seems like after landing from using up all of my Booster and immediately jumping the same frame I hit the floor, the Booster doesn't refuel.

**Comment by Yukitty** [comment]
The Whimsical Star doesn't seem as "reactive" to player movement as in the original. If you go through a door (so the stars kind of reset to a tight orbit around you) and then start walking, they generally would start swinging out in front and behind you without going upwards until you jump.

Also you can currently "stand on air" over the edge of a cliff without falling since the blockd is so high.

**Comment by isage** [comment]
I've cleaned/split the list above into different issues.

**Comment by B4rabbas** [comment]
Hi there, if needed I've made a correction of the french translation : there was few grammatical errror but a lot of misprint  (just look my repo if you want to implement it).

I've also an auto quit at the start of credits,

**Comment by kawa-yoiko** [comment]
In nxengine-evo, Life Capsules refill player's health, but in the original PC version it only increases remaining health by the capsule's value. I haven't purchased CS+ so I'm not sure how it behaves there.

Should there be a change? A 1+/1- will do.

https://github.com/nxengine/nxengine-evo/blob/5025ad1f3c84928b779ca01ec0390f3d360e8d6a/src/tsc.cpp#L881

**Comment by isage** [comment]
> In nxengine-evo, Life Capsules refill player's health, but in the original PC version it only increases remaining health by the capsule's value. I haven't purchased CS+ so I'm not sure how it behaves there.

Yeah, you're right. Fixed.
