### ISSUE TITLE
You cannot abort save/load menus.

### ISSUE THREAD

**Issue by Yukitty** [nxengine/nxengine-evo#55]
I keep accidentally hidding load instead of new game and as far as I know there's no way back to the title screen without loading a save and then resetting. The Esc button does nothing here, and both Jump and Shoot load the selected save file.

I'll understand if the save file can't be aborted for the sake of TSC scripts, since the TSC script would say "Game saved." next regardless of whether or not it actually did, but the loading screen should definitely be able to go back to the menu.

**Comment by isage** [comment]
Now jump and ESC aborts loading/saving screen.
We probably need to adjust all inputs in all menus accordingly, and maybe provide some hints on what which key does.

**Comment by Yukitty** [comment]
You cannot select "yes" with the fire button, you use jump for that. And then you use jump again to abort it? And then the TSC script doesn't abort so it says it saved even if you press Esc (which brings up the pause menu) and then close the pause menu. Hmm...

It would definitely be clearer if the script just straight up ended if you abort the save screen, but you might need to have a look at which buttons you use for confirming it. oo;

**Comment by isage** [comment]
Yeah, it's confusing and inconsistent right now.
In original game fire cancels (only in inventory, it seems), jump confirms.
But... but, i think it's the same as was with many games in NES era, when Japanese / West versions of game had A and B buttons switched around.
So i think we should instead use Fire/Enter everywhere to confirm and Jump/Esc to cancel.
In Yes/No dialog Jump should probably just highlight "No", instead of canceling right away.

Thoughts?

As for canceling "Game saved" script - there's a way, already built in: jump to script 0000 on cancel, same as Yes/No does.

**Comment by Yukitty** [comment]
Personally, I've always wanted to just split up doukutsu's multi-function buttons entirely into their own individual controls which _can_ overlap but don't necessarily have to.

That way I can separate "I want to shoot downwards" from "I want to turn around and make a question mark because there's nothing behind me" and have "cancel" on my gamepad's B button even though "fire" is actually on the X button. (the A button would still be both "ok" & "jump")

**Comment by isage** [comment]
That's an interesting idea. However, that would require scolling in
keybinding section of options (and translating new options into all
available languages).

Also, I'm away from internetz until Saturday, so I'll review PRs later.

**Comment by Yukitty** [comment]
That's fine, take your time. :3 Honestly you've already been waay more quick and responsive than I was expecting. It's been a pleasure working with you on something we're both so passionate about. (Even if I mess up a lot...)
